services:
  db:
    image: postgres:14-alpine
    container_name: flashcard-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: SuperSecretDevPassword123!
      POSTGRES_DB: flashcard_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
